version: '3'

services:
  api01: &api
    image: rinha-de-backend-2024-q1-rust
    hostname: api01
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/rinha
    ports:
      - "3001:3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:3000"
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '134MB'

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rinha 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256MB'

networks:
  default:
    driver: bridge
    name: frai-rinha-rust-2024q1
